name: ci workflow for python app test
on:
  push:
    branches:
      - "main"

jobs:
  nish-python-app-test:
    runs-on: ubuntu-latest
    steps:
      - name: checking python version on platform
        run: python -V